[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.12.15", features = ["debug-print", "runtime-tokio-native-tls", "sqlx-sqlite"] }

[dev-dependencies]
tokio = { version = "1.39.1", features = ["macros", "rt"] }